name: Promote to Final Repo

on:
  pull_request:
    types: [labeled]

jobs:
  promote:
    if: github.event.label.name == 'approved'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Software-Product-QA
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Clone main repo
        run: |
          git clone https://x-access-token:${{ secrets.FINAL_REPO_TOKEN }}@github.com/PranavPuranik-hub/final-Software-Product.git
        
      - name: Set remote with token
        run: |
          cd final-Software-Product
          git remote set-url origin https://x-access-token:${{ secrets.FINAL_REPO_TOKEN }}@github.com/PranavPuranik-hub/final-Software-Product.git

      - name: Create new branch
        run: |
          cd final-Software-Product
          git checkout -b auto-update-${{ github.run_id }}

      - name: Copy folder
        run: |
          mkdir -p final-Software-Product/folderF1
          cp -r folderF1/* final-Software-Product/folderF1/

      - name: Commit and push
        run: |
          cd final-Software-Product
          git add .
          git commit -m "Auto update from duplicate repo"
          git push origin HEAD

      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.FINAL_REPO_TOKEN }}
          path: final-Software-Product
          branch: auto-update-${{ github.run_id }}
          base: main
          title: "Auto PR from duplicate repo"
          body: "Created automatically after approval"